name: tpdm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - cfitsio=3.470=hb418390_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.6=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cryptography=41.0.2=py310h22a60cf_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py310h5eee18b_0
  - dask-core=2023.7.1=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=h9c3ff4c_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_h77c792f_102
  - fontconfig=2.14.1=hef1e5e3_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - future=0.18.3=pyhd8ed1ab_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=hf484d3e_1000
  - idna=3.4=py310h06a4308_0
  - imagecodecs=2021.8.26=py310h46e8fbd_2
  - imageio=2.31.1=pyh24c5eb1_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jpeg=9e=h5eee18b_1
  - jxrlib=1.1=h7f98852_2
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.6=h9c3ff4c_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libclang=10.0.1=default_hb85057a_2
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcurl=8.1.1=h251f7ec_1
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm10=10.0.1=he513fc3_3
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.52.0=h2d74bed_1
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - llvmlite=0.40.0=py310he621ea3_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=3.7.1=py310h06a4308_1
  - matplotlib-base=3.7.1=py310h1128e8f_1
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=pyhd8ed1ab_0
  - ninja=1.11.1=h924138e_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.57.1=py310h0f6aa51_0
  - numpy=1.23.3=py310h53a5b5f_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - partd=1.4.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.1.2=py310h06a4308_0
  - ply=3.11=py_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyfftw=0.12.0=py310h0885ff1_3
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.4.1=py310h5eee18b_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py310h06a4308_0
  - scikit-image=0.19.2=py310hb5077e9_0
  - scipy=1.9.3=py310h5f9d8c6_2
  - setuptools=67.8.0=py310h06a4308_0
  - sigpy=0.1.25=pyha21a80b_1
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h295c915_0
  - sporco=0.2.1=py310hff52083_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tifffile=2021.4.8=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchaudio=0.13.1=py310_cu117
  - torchmetrics=0.11.4=pyhd8ed1ab_0
  - torchvision=0.14.1=py310_cu117
  - tornado=6.1=py310h5764c6d_3
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing_extensions=4.6.3=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zfp=0.5.5=h9c3ff4c_8
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==1.4.0
      - contextlib2==21.6.0
      - ml-collections==0.1.1
      - pyqt5-sip==12.11.0
      - pyyaml==6.0.1
